[package]
name = "krakentet"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio ={ version="1.38.0", features=["full"]}
tokio-macros = "2.3.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
